export enum AppRoutes {
  ADMIN = 'admin',
  APPROVALS = 'approvals',
  AUTH_LOGOUT = 'auth/logout',
  CASH_REGISTER = 'cash-register',
  CHANGE_PASSWORD = 'change-password',
  CLIENTS = 'clients',
  CLIENTS_DETAIL = 'clients/:dni',
  CLIENTS_NEW = 'clients/new',
  COLLECTOR = 'collector',
  CONFIG = 'config',
  DASHBOARD = 'dashboard',
  DELINQUENCY = 'delinquency',
  FORGOT_PASSWORD = 'forgot-password',
  LOGIN = 'login',
  OPERATIONS = 'operations',
  OPERATIONS_DETAIL = 'operations/:id',
  OPERATIONS_NEW = 'operations/new',
  PRODUCTS = 'products',
  PRODUCTS_NEW = 'products/new',
  PRODUCTS_DETAIL = 'products/:id',
  PRODUCTS_EDIT = 'products/:id/edit',
  REPORTS = 'reports',
  ROUTE = '/collector/route',
  SELLER = 'seller',
  SHEET = 'sheet',
  USERS = 'users',
  USERS_DETAIL = 'users/:id',
  USERS_NEW = 'users/new',

  // Seller
  SELLER_OPERATIONS = 'seller/operations/new',
  SELLER_OPERATIONS_DETAIL = 'seller/operations/:id',
  SELLER_PRODUCTS = 'seller/products',
  SELLER_PRODUCTS_NEW = 'seller/products/new',
  SELLER_PRODUCTS_DETAIL = 'seller/products/:id',
  SELLER_PRODUCTS_EDIT = 'seller/products/:id/edit',
}
