export enum AppRoutes {
  ADMIN = 'admin',
  APPROVALS = 'approvals',
  AUTH_LOGOUT = 'auth/logout',
  CASH_REGISTER = 'cash-register',
  CHANGE_PASSWORD = 'change-password',
  CLIENTS = 'clients',
  CLIENTS_DETAIL = 'clients/:dni',
  CLIENTS_NEW = 'clients/new',
  COLLECTOR = 'collector',
  CONFIG = 'config',
  DASHBOARD = 'dashboard',
  DELINQUENCY = 'delinquency',
  FORGOT_PASSWORD = 'forgot-password',
  LOGIN = 'login',
  OPERATIONS = 'operations',
  OPERATIONS_NEW = 'operations/new',
  PRODUCTS = 'products',
  REPORTS = 'reports',
  ROUTE = '/collector/route',
  SELLER = 'seller',
  SHEET = 'sheet',
  USERS = 'users',
  USERS_DETAIL = 'users/:id',
  USERS_NEW = 'users/new',
}
